name: Rust

on:
  push:
    branches: [ "master", "feature-**", "patch-**" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
